language: ruby
rvm:
  - "2.2.1"
before_install:
  - sudo add-apt-repository ppa:jon-severinsson/ffmpeg -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsndfile1-dev libsox-fmt-all lame mp3val sox twolame
  - sudo apt-get install -qq ffmpeg
